#!/bin/sh

export scriptdir=`pwd`

export fcdate=`date -u +%Y%m%d`



scratchdir=/tmp/

export DATADIR=silam-dl
export email="spiderr.roma2@gmail.com"
export version="v6_1"

# Version-dependent THREDDS query parameters (v6_1 uses rotated pole with south pole at 0°E, 30°S)
export varlist="cnc_POLLEN_ALDER_m22,cnc_POLLEN_BIRCH_m22,cnc_POLLEN_GRASS_m32,cnc_POLLEN_MUGWORT_m18,cnc_POLLEN_OLIVE_m20,cnc_POLLEN_RAGWEED_m18"
export subset="&maxy=0&minx=12&maxx=28&miny=-15"
export vertCoord="1"
export accept="netcdf"

export gradsnc=`which grads`

export publish=false

# Geometry depends on the picture Upper-leftcorner of logo with respect
# to upper-left corner of a picture 
export PUTLOGOCMD="composite  -geometry  +77+465  $scriptdir/scale.png"
# Special logo for aqi and pollen index pictures
export PUTLOGOCMDINDEX="$PUTLOGOCMD"

#export outsuff=""
export suitename="UKR-pollen"

export OUTPUT_DIR=${scriptdir}/output-${suitename}
